server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: travelpulse-backend

  datasource:
    url: jdbc:mysql://localhost:3306/travelpulse_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

travelpulse:
  default-fuel-price-eur: 1.85
  default-consumption-l-per-100km: 6.5